language: python

python: 3.5

env:
    matrix:
      - TOXENV=py26
      - TOXENV=py27
      - TOXENV=py33
      - TOXENV=py34
      - TOXENV=py35
      - TOXENV=pypy
      - TOXENV=pypy3
      - TOXENV=flake8

script:
  - make test

install:
  - travis_retry pip install tox
